/**
 * Central German dictionary for the interactive tours (DE locale).
 *
 * Keeps the six scene files 100% untouched (EN byte-identical). The engine
 * (player.js) merges from here on the /de/ locale via isDE():
 *   TOUR_DE[tourId] = {
 *     tag, coverLabel, closing:{headline,sub},
 *     scenes: { [sceneId]: { title, body, i18n: [[en, de], …] } }
 *   }
 *
 * i18n pairs are applied to a scene's html with split/join (all occurrences),
 * scoped to that scene. Use phrases distinctive enough to avoid stray matches.
 *
 * Rules: Sie-Form, no em-dashes (→ comma), product/module names stay English
 * (Vero, ClaimIQ, ClearMatch, CollectPulse, CashPulse, DocSense), and mock DATA
 * stays — company names, invoice/PO numbers, amounts, dates, account codes,
 * and foreign-language transcripts (they demo the multilingual capability).
 */

export const TOUR_DE = {
  /* ═══════════════════════ CASH APP ═══════════════════════ */
  'cash-app': {
    tag: 'CASH APPLICATION · INTERAKTIVE DEMO',
    coverLabel: 'Cash Application in 30 Sekunden ansehen',
    closing: {
      headline: 'Das sind 90 % der Cash Application, <span class="grad">automatisiert</span>.',
      sub: 'Möchten Sie es auf Ihren eigenen Daten sehen?',
    },
    scenes: {
      '01-inbox': {
        title: 'Schritt 1 · Posteingang',
        body: 'Drei Zahlungsavise sind über Nacht eingegangen. Vero hat mit dem ersten bereits begonnen.',
        i18n: [
          ['<h2>Inbox</h2>', '<h2>Posteingang</h2>'],
          ['3 unread · today', '3 ungelesen · heute'],
          [' · Accounts Payable', ' · Kreditorenbuchhaltung'],
          ['Remittance advice — Wire transfer €530,000 — 3 invoices', 'Zahlungsavis, Überweisung €530.000, 3 Rechnungen'],
          ['Payment notification — Invoices INV-0014, INV-0017', 'Zahlungsbenachrichtigung, Rechnungen INV-0014, INV-0017'],
          [' · Finance', ' · Finanzen'],
          ['2 min ago', 'vor 2 Min.'],
          ['14 min ago', 'vor 14 Min.'],
          ['42 min ago', 'vor 42 Min.'],
        ],
      },
      '02-extract': {
        title: 'Schritt 2 · Extraktion',
        body: 'Jedes Feld mit <span class="grad">Treffersicherheit</span> extrahiert. Keine Vorlagen zu pflegen.',
        i18n: [
          ['Acme Industries — remittance.pdf', 'Acme Industries, remittance.pdf'],
          ['DocSense · processing', 'DocSense · Verarbeitung'],
          ['>Extracted fields <', '>Extrahierte Felder <'],
          ['6 / 6 captured', '6 / 6 erfasst'],
          ['<span class="field-key">Vendor</span>', '<span class="field-key">Lieferant</span>'],
          ['<span class="field-key">Amount</span>', '<span class="field-key">Betrag</span>'],
          ['<span class="field-key">Currency</span>', '<span class="field-key">Währung</span>'],
          ['<span class="field-key">Bank ref</span>', '<span class="field-key">Bankreferenz</span>'],
          ['<span class="field-key">Invoices</span>', '<span class="field-key">Rechnungen</span>'],
          ['<span class="field-key">Value date</span>', '<span class="field-key">Wertstellung</span>'],
        ],
      },
      '03-match': {
        title: 'Schritt 3 · Auto-Abgleich',
        body: 'Drei Rechnungen, drei Treffer. <span class="grad">€530 Tsd. zugeordnet</span> in unter 4 Sekunden.',
        i18n: [
          ['Auto-match results', 'Auto-Abgleich-Ergebnisse'],
          [' · run 3.7s', ' · Dauer 3,7 s'],
          ['>Auto-matched<', '>Automatisch zugeordnet<'],
          ['>Invoices cleared<', '>Rechnungen ausgeglichen<'],
          ['>Avg confidence<', '>Ø Sicherheit<'],
          ['Acme Industries · 30 days', 'Acme Industries · 30 Tage'],
          ['Match 99%', 'Treffer 99 %'],
        ],
      },
      '04-edge': {
        title: 'Schritt 4 · Grenzfall',
        body: 'Dieser ist grenzwertig. Vero legt ihn vor, <span class="grad">Sie entscheiden</span> mit einem Klick.',
        i18n: [
          ['3 of 4 matched', '3 von 4 zugeordnet'],
          [' · cleared</span>', ' · ausgeglichen</span>'],
          ['Acme Industries · 45 days · expected €92,000', 'Acme Industries · 45 Tage · erwartet €92.000'],
          ['87% · short by €230', '87 % · Kürzung €230'],
          ['>Most likely<', '>Wahrscheinlichste Ursache<'],
          ['Trade promotion deduction', 'Trade-Promotion-Abzug'],
          ['Q2 promo TP-041 active for this account', 'Q2-Promo TP-041 für dieses Konto aktiv'],
          ['Pricing discrepancy', 'Preisabweichung'],
          ['No POD discrepancy on file', 'Keine POD-Abweichung hinterlegt'],
          ['Vero recommends accepting trade promo', 'Vero empfiehlt, den Trade-Promo zu akzeptieren'],
          ['Confirm match', 'Treffer bestätigen'],
        ],
      },
      '05-je': {
        title: 'Schritt 5 · Journalbuchung',
        body: 'Journalbuchung erstellt, Audit-Trail angehängt. Ein Klick, um <span class="grad">in ERP zu buchen</span>.',
        i18n: [
          ['Journal entry · ready to post', 'Journalbuchung · bereit zum Buchen'],
          ['Auto-assembled · 4 lines · balances', 'Automatisch erstellt · 4 Zeilen · ausgeglichen'],
          ['Cash receipt · Acme Industries', 'Zahlungseingang · Acme Industries'],
          ['>Balanced</span>', '>Ausgeglichen</span>'],
          ['<th>Account</th>', '<th>Konto</th>'],
          ['<th>Description</th>', '<th>Beschreibung</th>'],
          ['>Debit</th>', '>Soll</th>'],
          ['>Credit</th>', '>Haben</th>'],
          [' · AR · Acme', ' · Debitoren · Acme'],
          ['Wire receipt 22 Apr', 'Überweisungseingang 22. Apr'],
          ['>Clear INV-0019<', '>INV-0019 ausgleichen<'],
          ['>Clear INV-0020<', '>INV-0020 ausgleichen<'],
          ['>Clear INV-0021 + INV-0023 net<', '>INV-0021 + INV-0023 netto ausgleichen<'],
          ['>Totals<', '>Summen<'],
          ['4 source docs linked', '4 Belege verknüpft'],
          ['Approval thresholds met', 'Freigabegrenzen erfüllt'],
          ['SAP S/4 connector ready', 'SAP-S/4-Konnektor bereit'],
          ['Post to ERP →', 'In ERP buchen →'],
        ],
      },
      '06-posted': {
        title: 'Schritt 6 · Gebucht',
        body: 'Vero hat erkannt, dass das ein tägliches Muster ist. Soll Vero jeden Morgen übernehmen?',
        i18n: [
          ['Posted to SAP S/4', 'In SAP S/4 gebucht'],
          [' · cleared 4 invoices · journal balanced', ' · 4 Rechnungen ausgeglichen · Journal ausgeglichen'],
          ['>End-to-end<', '>Ende-zu-Ende<'],
          ['>Cleared<', '>Ausgeglichen<'],
          ['>Manual touches<', '>Manuelle Eingriffe<'],
          ['Acme sends like this every morning. Want me to handle them automatically from now on?', 'Acme sendet jeden Morgen so. Soll ich das ab jetzt automatisch übernehmen?'],
          ['Yes, automate', 'Ja, automatisieren'],
          ['Not now', 'Jetzt nicht'],
        ],
      },
      '07-schedule': {
        title: 'Schritt 7 · Zeitplan',
        body: 'Vero schlägt die Regeln vor. <span class="grad">Sie behalten die Kontrolle</span> über jeden Schwellenwert.',
        i18n: [
          ['Set up daily run', 'Täglichen Zeitplan einrichten'],
          ['Vero proposes, you approve every detail', 'Vero schlägt vor, Sie geben jedes Detail frei'],
          [' Trigger</div>', ' Auslöser</div>'],
          ['Email arrives in inbox · vendor matches "Acme"', 'E-Mail trifft im Posteingang ein · Lieferant entspricht „Acme"'],
          [' Action</div>', ' Aktion</div>'],
          ['Extract, match, post journal entry', 'Extrahieren, zuordnen, Journalbuchung buchen'],
          [' Confidence threshold</div>', ' Sicherheitsschwelle</div>'],
          ['≥ 95% auto-post · 80 to 94% surface to you', '≥ 95 % automatisch buchen · 80 bis 94 % Ihnen vorlegen'],
          [' Schedule</div>', ' Zeitplan</div>'],
          ['Run within 5 min of arrival · check every 8:00 AM', 'Innerhalb von 5 Min. nach Eingang · täglich um 8:00 Uhr prüfen'],
          ['Pauseable · auditable · changes logged', 'Pausierbar · auditierbar · Änderungen protokolliert'],
          ['Approve & schedule', 'Freigeben & planen'],
          ['>Edit</span>', '>Bearbeiten</span>'],
        ],
      },
      '08-done': {
        title: 'Schritt 8 · Live',
        body: 'Fertig. Vero erledigt es morgen um <span class="grad">8:00 Uhr</span> und jeden Morgen danach.',
        i18n: [
          ['Live in the cockpit', 'Live im Cockpit'],
          ["Vero is now watching the inbox. You'll see results in tomorrow's morning briefing.", 'Vero überwacht jetzt den Posteingang. Ergebnisse sehen Sie im morgigen Tagesbriefing.'],
          [' · Daily Cash Application', ' · Tägliche Cash Application'],
          ['Configured by you · 22 Apr', 'Von Ihnen konfiguriert · 22. Apr'],
          ['>Next run<', '>Nächste Ausführung<'],
          ['>Last processed<', '>Zuletzt verarbeitet<'],
          ['>Auto-post threshold<', '>Automatik-Schwelle<'],
          ['8:00 AM', '8:00 Uhr'],
          ['\n              Active\n', '\n              Aktiv\n'],
        ],
      },
    },
  },

  /* ═══════════════════════ COLLECTIONS ═══════════════════════ */
  'collections': {
    tag: 'COLLECTIONS · INTERAKTIVE DEMO',
    coverLabel: 'Collections in 30 Sekunden ansehen',
    closing: {
      headline: '8 Zahlungszusagen erfasst. 3 Eskalationen weitergeleitet. <span class="grad">Stunden zurück.</span>',
      sub: 'Soll Vero Ihren Morgen-Arbeitsvorrat übernehmen, jeden Morgen?',
    },
    scenes: {
      'c-01-worklist': {
        title: 'Schritt 1 · Arbeitsvorrat',
        body: '8 Konten sind heute überfällig. Vero bearbeitet alle gleichzeitig: Anrufe in <span class="grad">ihrer Sprache</span>, E-Mails in Ihrem Ton.',
        i18n: [
          ['>Overdue worklist</h2>', '>Überfällige Posten</h2>'],
          [' accounts · €475K past due · updated 2 min ago', ' Konten · €475 Tsd. überfällig · vor 2 Min. aktualisiert'],
          ['Run batch (', 'Sammellauf starten ('],
          ['>Accounts overdue<', '>Überfällige Konten<'],
          ['Sorted by days overdue · descending', 'Sortiert nach Tagen überfällig · absteigend'],
          ['Last touch · next action', 'Letzter Kontakt · nächste Aktion'],
          ['>Last Fri<', '>Letzten Fr<'],
          ['>Never<', '>Nie<'],
          ['>Email sent<', '>E-Mail gesendet<'],
          ['>3d ago<', '>vor 3 T<'],
          ['>Call Thu<', '>Anruf Do<'],
          ['>1w ago<', '>vor 1 Wo<'],
        ],
      },
      'c-02-batch': {
        title: 'Schritt 2 · Sammellauf',
        body: 'Ein Arbeitsvorrat, 8 parallele Workstreams. Vero folgt Ihrem <span class="grad">Playbook</span> für jedes: Kanal, Sprache, Eskalationsregeln.',
        i18n: [
          ['>Batch running</h2>', '>Sammellauf läuft</h2>'],
          [' accounts in flight · calls in native language, emails localized', ' Konten in Bearbeitung · Anrufe in Landessprache, E-Mails lokalisiert'],
          ['● Live', '● Live'],
          ['Vero is working the queue', 'Vero arbeitet den Arbeitsvorrat ab'],
          ['Playbook v3 · 5 languages active', 'Playbook v3 · 5 Sprachen aktiv'],
          ['● Queued', '● In Warteschlange'],
          ['● Calling', '● Anruf läuft'],
          ['● Emailing', '● E-Mail läuft'],
          ['✓ PTP €179K', '✓ Zahlungszusage €179 Tsd.'],
          ['✉ Email sent', '✉ E-Mail gesendet'],
          ['⚠ Escalated', '⚠ Eskaliert'],
          ['✓ PTP €14K', '✓ Zahlungszusage €14 Tsd.'],
          ['✓ Paid today', '✓ Heute bezahlt'],
          ['✉ Reminder sent', '✉ Erinnerung gesendet'],
        ],
      },
      'c-03-ptp': {
        title: 'Schritt 3 · Zahlungszusage',
        body: 'Maria bei Oceanic Energy hat <span class="grad">€179 Tsd.</span> bis Freitag zugesagt. Protokolliert, mit vollständigem Transkript.',
        i18n: [
          ['Resolved · autonomous', 'Geklärt · autonom'],
          ['>Worklist<', '>Arbeitsvorrat<'],
          [' accounts · 1 focused', ' Konten · 1 im Fokus'],
          ['PTP €179K', 'Zahlungszusage €179 Tsd.'],
          ['AI call · 3:42', 'KI-Anruf · 3:42'],
          ['Positive sentiment', 'Positive Stimmung'],
          ['Portuguese', 'Portugiesisch'],
          ['Auto-translated: "I can wire €179,000 by Friday. Invoice reference 0019, as always."', 'Automatisch übersetzt: „Ich kann €179.000 bis Freitag überweisen. Rechnungsreferenz 0019, wie immer."'],
          ['Promise to pay logged', 'Zahlungszusage protokolliert'],
          ['Reminder scheduled for Thu, 24 Apr', 'Erinnerung geplant für Do, 24. Apr'],
          ['Due Fri 25 Apr', 'Fällig Fr 25. Apr'],
        ],
      },
      'c-04-fallback': {
        title: 'Schritt 4 · Rückfallebene',
        body: 'Keine Antwort? Vero wechselt zur E-Mail, in ihrer Sprache, <span class="grad">nach Ihren Regeln</span>, ohne Nachfrage.',
        i18n: [
          ['Reminder sent · autonomous', 'Erinnerung gesendet · autonom'],
          ['>Worklist<', '>Arbeitsvorrat<'],
          [' accounts · 1 focused', ' Konten · 1 im Fokus'],
          ['>Email sent<', '>E-Mail gesendet<'],
          ['>AI call</div>', '>KI-Anruf</div>'],
          ['No answer · 2 tries', 'Keine Antwort · 2 Versuche'],
          ['>Email</div>', '>E-Mail</div>'],
          ['Sent · 08:42 GMT', 'Gesendet · 08:42 GMT'],
          ['Escalation ladder', 'Eskalationsstufen'],
          ['Voicemail → email (EN template) → call tomorrow 09:00 → escalate +1 level', 'Mailbox, dann E-Mail (EN-Vorlage), dann Anruf morgen 09:00, dann +1 Eskalationsstufe'],
        ],
      },
      'c-05-escalation': {
        title: 'Schritt 5 · Eskalation',
        body: 'Drei Konten, die Vero nicht automatisch klären sollte. Jedes landet in <span class="grad">Ihrer Prüfliste</span> mit dem vollständigen Nachweispaket.',
        i18n: [
          ['>Escalations</h2>', '>Eskalationen</h2>'],
          [' accounts processed · 3 need your call', ' Konten verarbeitet · 3 brauchen Ihre Entscheidung'],
          [' Action required', ' Aktion erforderlich'],
          ['3 disputes detected · needs you', '3 Streitfälle erkannt · brauchen Sie'],
          ['Vero packaged the full evidence per case. Review and respond at your own pace.', 'Vero hat pro Fall die vollständigen Nachweise gebündelt. Prüfen und antworten Sie in Ihrem Tempo.'],
          ['Review queue →', 'Prüfliste öffnen →'],
          ['⚠ Escalated', '⚠ Eskaliert'],
          ['PTP €179K', 'Zahlungszusage €179 Tsd.'],
          ['>Email sent<', '>E-Mail gesendet<'],
          ['PTP €14K', 'Zahlungszusage €14 Tsd.'],
          ['>Paid today<', '>Heute bezahlt<'],
          ['>Reminder sent<', '>Erinnerung gesendet<'],
          ['Price disagreement on PO 4421', 'Preisunstimmigkeit bei Bestellung 4421'],
          ['Short-pay €4,230 · trade promo?', 'Kürzung €4.230 · Trade-Promo?'],
          ['Invoice disputed · subscription cadence', 'Rechnung strittig · Abo-Rhythmus'],
        ],
      },
      'c-06-done': {
        title: 'Schritt 6 · Fertig',
        body: 'Acht Minuten Vero. Stunden gespart, <span class="grad">jeden Morgen</span>, wenn Sie möchten.',
        i18n: [
          ['Morning queue clear', 'Morgen-Arbeitsvorrat erledigt'],
          ["Every contact made, every outcome logged. Here's what happened.", 'Jeder Kontakt erledigt, jedes Ergebnis protokolliert. Das ist passiert.'],
          ["Today's collection run", 'Heutiger Collections-Durchlauf'],
          ['Complete · 8 min', 'Abgeschlossen · 8 Min.'],
          ['>PTPs captured<', '>Zahlungszusagen erfasst<'],
          ['>Cash secured<', '>Liquidität gesichert<'],
          ['>Escalated to you<', '>An Sie eskaliert<'],
          ['>Manual touches<', '>Manuelle Eingriffe<'],
          ['Your morning queue is clear. Want me to run this every day at 08:00?', 'Ihr Morgen-Arbeitsvorrat ist erledigt. Soll ich das jeden Tag um 08:00 ausführen?'],
          ['Yes, automate', 'Ja, automatisieren'],
          ['Not now', 'Jetzt nicht'],
        ],
      },
    },
  },

  /* ═══════════════════════ DEDUCTIONS ═══════════════════════ */
  'deductions': {
    tag: 'DEDUCTIONS · INTERAKTIVE DEMO',
    coverLabel: 'Deductions in 30 Sekunden ansehen',
    closing: {
      headline: 'Kürzung untersucht, Ausgleich gebucht. <span class="grad">Stunden gespart.</span>',
      sub: 'Soll Vero Muster automatisch klären, die es schon kennt?',
    },
    scenes: {
      'd-01-queue': {
        title: 'Schritt 1 · Abzugsliste',
        body: 'Acme Retail hat <span class="grad">€4.230</span> auf einer Rechnung über €92 Tsd. gekürzt. Vero holt die Nachweise.',
        i18n: [
          ['>Deduction queue</h2>', '>Abzugsliste</h2>'],
          [' open · €8,680 disputed · auto-classification running', ' offen · €8.680 strittig · Auto-Klassifizierung läuft'],
          [' unresolved</span>', ' ungeklärt</span>'],
          ['Open short-pays + disputes', 'Offene Kürzungen + Streitfälle'],
          ['Oldest first · click Investigate to trigger classification', 'Älteste zuerst · Untersuchen anklicken, um die Klassifizierung zu starten'],
          ['>Action</span>', '>Aktion</span>'],
          ['Short-pay · possible trade promo', 'Kürzung · möglicher Trade-Promo'],
          ['Price disagreement on PO 4421', 'Preisunstimmigkeit bei Bestellung 4421'],
          ['Subscription cadence mismatch', 'Abo-Rhythmus stimmt nicht'],
          ['Quality claim · SKU 8842', 'Qualitätsreklamation · SKU 8842'],
          ['Unexpected shipping fee', 'Unerwartete Versandkosten'],
          [' ago</div>', ' her</div>'],
          ['>France</span>', '>Frankreich</span>'],
          ['>Spain</span>', '>Spanien</span>'],
          ['>Ireland</span>', '>Irland</span>'],
          ['>Sweden</span>', '>Schweden</span>'],
          ['>Netherlands</span>', '>Niederlande</span>'],
          ['>Investigate →</button>', '>Untersuchen →</button>'],
          ['>Investigate</button>', '>Untersuchen</button>'],
        ],
      },
      'd-02-evidence': {
        title: 'Schritt 2 · Beweiskette',
        body: 'Vero holt Rechnung, Bestellung, Liefernachweis, Vertrag und jede aktive <span class="grad">Trade-Promo-Vereinbarung</span> und verknüpft sie automatisch.',
        i18n: [
          ['Invoice INV-3482 · €92,000 · paid €87,770 · ', 'Rechnung INV-3482 · €92.000 · bezahlt €87.770 · '],
          ['short €4,230</span>', 'Kürzung €4.230</span>'],
          ['● Classifying', '● Klassifizierung'],
          ['>Invoice</div>', '>Rechnung</div>'],
          ['>Customer PO</div>', '>Kunden-Bestellung</div>'],
          ['>Proof of delivery</div>', '>Liefernachweis</div>'],
          ['>Contract</div>', '>Vertrag</div>'],
          ['>Trade promo</div>', '>Trade-Promo</div>'],
          ['TP-041 · active', 'TP-041 · aktiv'],
          ['5 sources linked · ', '5 Quellen verknüpft · '],
          [' historical cases</span> cross-referenced · classification in 2.8s', ' historische Fälle</span> abgeglichen · Klassifizierung in 2,8 s'],
        ],
      },
      'd-03-recommend': {
        title: 'Schritt 3 · Veros Plan',
        body: 'Nachweise zusammengestellt, Plan entworfen. <span class="grad">Ein Klick</span> zum Anwenden.',
        i18n: [
          ['Vero · Classification complete', 'Vero · Klassifizierung abgeschlossen'],
          [' · short €4,230', ' · Kürzung €4.230'],
          ['Ready to apply', 'Bereit zum Anwenden'],
          ["Here's what I'd do:", 'Das würde ich tun:'],
          ['Based on 5 source documents and 1,247 historical cases.', 'Basierend auf 5 Quelldokumenten und 1.247 historischen Fällen.'],
          ['Auto-settle as trade promo TP-041', 'Automatisch als Trade-Promo TP-041 ausgleichen'],
          ['89% match · write off to promo reserve · 14 similar cases this quarter', '89 % Übereinstimmung · Ausbuchung auf Promo-Rückstellung · 14 ähnliche Fälle dieses Quartal'],
          ['Route to your queue with summary', 'Mit Zusammenfassung in Ihre Prüfliste leiten'],
          ['No matching promo, PO, or POD note. Needs a human call', 'Kein passender Promo, keine Bestellung, kein POD-Vermerk. Braucht eine menschliche Entscheidung'],
          ['5 docs</strong> searched', '5 Belege</strong> durchsucht'],
          ['2.8s</strong> classification', '2,8 s</strong> Klassifizierung'],
          ['GL balanced</strong> · SAP ready', 'Sachkonto ausgeglichen</strong> · SAP bereit'],
          ['Audit trail</strong> preserved', 'Audit-Trail</strong> erhalten'],
          ['Every step auditable. You can roll back any settlement from the queue.', 'Jeder Schritt auditierbar. Sie können jeden Ausgleich aus der Liste zurücknehmen.'],
          ['Review details', 'Details prüfen'],
          ["Apply Vero's plan →", 'Veros Plan anwenden →'],
        ],
      },
      'd-04-done': {
        title: 'Schritt 4 · Gebucht',
        body: 'In unter 5 Minuten geklärt. Vero hat <span class="grad">14 ähnliche Fälle</span> dieses Quartal erkannt. Soll Vero die automatisch klären?',
        i18n: [
          ['>Settlement posted</h3>', '>Ausgleich gebucht</h3>'],
          ['€3,780 written off to trade promo. €450 routed to your queue with summary + evidence.', '€3.780 auf Trade-Promo ausgebucht. €450 mit Zusammenfassung und Nachweisen in Ihre Prüfliste geleitet.'],
          ["Today's deduction pass", 'Heutiger Abzugs-Durchlauf'],
          ['Complete · 4:12', 'Abgeschlossen · 4:12'],
          ['>Settled<', '>Ausgeglichen<'],
          ['>Auto-resolved<', '>Automatisch geklärt<'],
          ['>Routed to you<', '>An Sie geleitet<'],
          ['>Docs linked<', '>Belege verknüpft<'],
          ['14 other short-pays this quarter match TP-041 above 95% confidence. Want me to auto-resolve those too?', '14 weitere Kürzungen dieses Quartal passen zu TP-041 über 95 % Sicherheit. Soll ich die auch automatisch klären?'],
          ['Yes, auto-resolve', 'Ja, automatisch klären'],
          ['Not now', 'Jetzt nicht'],
        ],
      },
    },
  },

  /* ═══════════════════════ VERO CHAT ═══════════════════════ */
  'vero-chat': {
    tag: 'VERO CHAT · INTERAKTIVE DEMO',
    coverLabel: 'Vero Chat in 30 Sekunden ansehen',
    closing: {
      headline: 'Fragen Sie alles. Antworten und <span class="grad">Aktionen</span>.',
      sub: 'Soll Vero Ihre Risikolandschaft überwachen und Sie jeden Morgen briefen?',
    },
    scenes: {
      'v-01-ask': {
        title: 'Schritt 1 · Fragen',
        body: 'Stellen Sie jede Frage. Vero greift auf Ihre <span class="grad">Live-Daten</span> zu. Kein SQL, keine Joins, kein Warten auf BI.',
        i18n: [
          ['● Ready · access to ledger, comms, forecasts', '● Bereit · Zugriff auf Hauptbuch, Kommunikation, Prognosen'],
          ['Hi Sarah, what would you like to know?', 'Hallo Sarah, was möchten Sie wissen?'],
          ['Ask in plain English. I have full read access to your AR, your bank, your forecasts, and every customer email and call.', 'Fragen Sie in natürlicher Sprache. Ich habe vollen Lesezugriff auf Ihre Debitoren, Ihre Bank, Ihre Prognosen und jede Kunden-E-Mail und jeden Anruf.'],
          ['Show me overdue accounts', 'Überfällige Konten anzeigen'],
          ["What's our DSO trend?", 'Wie ist unser DSO-Trend?'],
          ['Run the morning briefing', 'Morgen-Briefing ausführen'],
          ['Which customers are most at risk this quarter?', 'Welche Kunden sind dieses Quartal am stärksten gefährdet?'],
        ],
      },
      'v-02-thinking': {
        title: 'Schritt 2 · Analyse',
        body: 'Vero ruft die richtigen Tools auf (Fälligkeitsbericht, Kreditbewertung, Kommunikationshistorie) <span class="grad">parallel</span>.',
        i18n: [
          ['● Working · 3 tools in flight', '● Arbeitet · 3 Tools aktiv'],
          ['Which customers are most at risk this quarter?', 'Welche Kunden sind dieses Quartal am stärksten gefährdet?'],
          ['Looking at risk this quarter… let me pull a few things.', 'Ich sehe mir das Risiko für dieses Quartal an, ich hole ein paar Dinge.'],
          ['>Calling tools</div>', '>Tools werden aufgerufen</div>'],
          ['2 of 3 done · 1.4s', '2 von 3 fertig · 1,4 s'],
          ['1,247 invoices · €4.2M open', '1,247 Rechnungen · €4,2 Mio. offen'],
          ['5 above 50% slip risk', '5 über 50 % Ausfallrisiko'],
          ['scanning 384 emails + 47 calls…', 'durchsuche 384 E-Mails + 47 Anrufe…'],
          ['Ask Vero anything…', 'Vero etwas fragen…'],
        ],
      },
      'v-03-answer': {
        title: 'Schritt 3 · Antwort',
        body: 'Sortiert, bewertet, mit dem Warum. Die Aktions-Chips sind <span class="grad">ein Klick</span>. Nicht nur eine Antwort, ein Angebot zu handeln.',
        i18n: [
          ['● Ready · 3 tools done · 2.1s', '● Bereit · 3 Tools fertig · 2,1 s'],
          ['Which customers are most at risk this quarter?', 'Welche Kunden sind dieses Quartal am stärksten gefährdet?'],
          ['Five customers stand out. Total exposure is ', 'Fünf Kunden stechen heraus. Das Gesamtrisiko beträgt '],
          ['</span> across these accounts. Top one is <strong>', '</span> über diese Konten. An der Spitze steht <strong>'],
          ["</strong>: they've broken 2 PTPs in 60 days and sentiment is shifting.", '</strong>: 2 Zahlungszusagen in 60 Tagen gebrochen, die Stimmung kippt.'],
          ['2 broken PTPs · sentiment declining', '2 gebrochene Zahlungszusagen · Stimmung sinkt'],
          ['DSO trend +9 days · last call 12d ago', 'DSO-Trend +9 Tage · letzter Anruf vor 12 T'],
          ['New CFO · payment behavior unclear', 'Neuer CFO · Zahlungsverhalten unklar'],
          ['+ 2 more (Acme Tech, Acme Build)', '+ 2 weitere (Acme Tech, Acme Build)'],
          ['Schedule calls for top 3', 'Anrufe für Top 3 planen'],
          ['Email risk report to controller', 'Risikobericht an Controller mailen'],
          ['Add to morning briefing', 'Zum Morgen-Briefing hinzufügen'],
          ['Or ask a follow-up: "show me all communications with Acme Energy" works too.', 'Oder stellen Sie eine Folgefrage: „zeig mir alle Kommunikation mit Acme Energy" geht auch.'],
          ['Ask a follow-up…', 'Folgefrage stellen…'],
        ],
      },
      'v-04-done': {
        title: 'Schritt 4 · Fertig',
        body: 'Drei Anrufe mit <span class="grad">einem Klick</span> geplant. Soll Vero Risiken markieren und Sie jeden Morgen briefen?',
        i18n: [
          ['● Ready · 3 calls scheduled · 0:00:8', '● Bereit · 3 Anrufe geplant · 0:00:8'],
          ["Done. I scheduled three light-touch verification calls for tomorrow morning, in each customer's language. Here's the queue:", 'Erledigt. Ich habe drei kurze Bestätigungsanrufe für morgen früh geplant, jeweils in der Sprache des Kunden. Hier ist die Liste:'],
          ['Tomorrow · 09:00 onwards', 'Morgen · ab 09:00'],
          ['3 calls queued', '3 Anrufe in Warteschlange'],
          ['Light-touch · re-confirm Fri payment timing', 'Kurzkontakt · Fr-Zahlungstermin bestätigen'],
          ['Check on aging · DSO trend', 'Fälligkeiten prüfen · DSO-Trend'],
          ['Intro to new CFO · payment cadence', 'Vorstellung beim neuen CFO · Zahlungsrhythmus'],
          ['>Portuguese</span>', '>Portugiesisch</span>'],
          ['>German</span>', '>Deutsch</span>'],
          ['>English</span>', '>Englisch</span>'],
          ["Want me to flag risk shifts and brief you every morning at 08:00? I'll only act on signals you approve in advance.", 'Soll ich Risikoänderungen markieren und Sie jeden Morgen um 08:00 briefen? Ich handle nur bei Signalen, die Sie vorab freigeben.'],
          ['Yes, brief me daily', 'Ja, täglich briefen'],
          ['Just notify me', 'Nur benachrichtigen'],
          ['Ask a follow-up…', 'Folgefrage stellen…'],
        ],
      },
    },
  },

  /* ═══════════════════════ PREDICTIONS ═══════════════════════ */
  'predictions': {
    tag: 'CASH FLOW FORECASTING · INTERAKTIVE DEMO',
    coverLabel: 'Cash-Prognose in 30 Sekunden ansehen',
    closing: {
      headline: 'Ein Einbruch von €170 Tsd. vermieden. Prognose wieder auf Kurs. <span class="grad">Stunden zurück.</span>',
      sub: 'Soll Vero jeden Morgen Signale überwachen und darauf reagieren?',
    },
    scenes: {
      'p-01-forecast': {
        title: 'Schritt 1 · 13-Wochen-Liquiditätsplanung',
        body: 'Liquidität bleibt stark, bis auf einen <span class="grad">Einbruch von €170 Tsd.</span> in Woche 6. Vero hat das Risiko erkannt, bevor es eintritt.',
        i18n: [
          ['>13-week cash forecast</h2>', '>13-Wochen-Liquiditätsplanung</h2>'],
          ['AR + AP combined · 4 currencies · 12 entities · 1,247 open invoices · updated 14 min ago', 'Debitoren + Kreditoren · 4 Währungen · 12 Einheiten · 1,247 offene Rechnungen · vor 14 Min. aktualisiert'],
          ['● Live · Vero monitoring', '● Live · Vero überwacht'],
          ['Projected cash position · weeks 1–13', 'Prognostizierte Liquidität · Wochen 1 bis 13'],
          ['>Actuals</span>', '>Ist-Werte</span>'],
          ['>Forecast</span>', '>Prognose</span>'],
          ['>Confidence</span>', '>Sicherheit</span>'],
          ['>Week 13 forecast<', '>Woche-13-Prognose<'],
          ['+27% vs today', '+27 % ggü. heute'],
          ['>Week 6 dip<', '>Woche-6-Einbruch<'],
          ['>vs trend line<', '>ggü. Trendlinie<'],
          ['>Confidence</div>', '>Sicherheit</div>'],
          ['±€42K margin', '±€42 Tsd. Spanne'],
          ['Week 6 cash drops €170K below trend', 'Liquidität in Woche 6 fällt €170 Tsd. unter den Trend'],
          ["5 invoices at risk · driven by Acme Energy's €179K PTP slipping", '5 Rechnungen gefährdet · getrieben durch die rutschende €179 Tsd.-Zahlungszusage von Acme Energy'],
          ['Investigate →', 'Untersuchen →'],
        ],
      },
      'p-02-scenario': {
        title: 'Schritt 2 · Stresstest',
        body: '<span class="grad">Klicken Sie ein Szenario an</span>. Diagramm und Zahlen aktualisieren sich live. Wechseln Sie und drehen Sie die Intensität hoch.',
        i18n: [
          ['>Stress-test the forecast</h2>', '>Prognose im Stresstest</h2>'],
          ['Model FX, input costs, customer delays · AR + AP both included', 'FX, Inputkosten, Kundenverzögerungen modellieren · Debitoren + Kreditoren enthalten'],
          ['Scenario builder · live', 'Szenario-Builder · live'],
          ['FX shift', 'FX-Wechsel'],
          ['Input costs', 'Inputkosten'],
          ['DSO drift', 'DSO-Drift'],
          ['Customer delay', 'Kundenverzögerung'],
          ['EUR strengthens 5% vs USD', 'EUR gewinnt 5 % ggü. USD'],
          ['Affects US revenue conversion · Q ends in week 13', 'Betrifft US-Umsatzumrechnung · Quartal endet in Woche 13'],
          ['>Baseline</span>', '>Basislinie</span>'],
          ['>Scenario</span>', '>Szenario</span>'],
          ['>Intensity</span>', '>Intensität</span>'],
          ['US receivables book: $1.2M · locked at €0.92 · adjustment applied from week 4', 'US-Forderungsbuch: $1.2M · fixiert bei €0.92 · Anpassung ab Woche 4'],
          ['Week 13 · baseline', 'Woche 13 · Basislinie'],
          ['>unchanged</div>', '>unverändert</div>'],
          ['Week 13 · scenario', 'Woche 13 · Szenario'],
          [' exposure</div>', ' Risiko</div>'],
          ['>Cash at risk<', '>Liquidität in Gefahr<'],
          ['>USD receivables</div>', '>USD-Forderungen</div>'],
          ['Pick a scenario and click through the intensities, then see the invoices at risk', 'Wählen Sie ein Szenario, klicken Sie die Intensitäten durch und sehen Sie dann die gefährdeten Rechnungen'],
          ['Chart and numbers update live · no save / reload · swap scenarios as often as you like', 'Diagramm und Zahlen aktualisieren live · kein Speichern / Neuladen · beliebig oft wechseln'],
          ['See invoices at risk →', 'Gefährdete Rechnungen ansehen →'],
        ],
      },
      'p-03-atrisk': {
        title: 'Schritt 3 · Gefährdete Rechnungen',
        body: 'Die €179 Tsd. von Acme Energy sind das größte Risiko. <span class="grad">88 % Rutschwahrscheinlichkeit</span> aus Verhalten und Signalen.',
        i18n: [
          ['>Week 6 · at-risk invoices</h2>', '>Woche 6 · gefährdete Rechnungen</h2>'],
          ['Sorted by risk score · likelihood of slipping past due date', 'Sortiert nach Risiko-Score · Wahrscheinlichkeit, überfällig zu werden'],
          [' 5 to review', ' 5 zu prüfen'],
          ['Week 6 expected receipts: €870K · forecast: €700K', 'Erwartete Eingänge Woche 6: €870 Tsd. · Prognose: €700 Tsd.'],
          ['€170K shortfall driven by these 5 invoices · click any row to dig in', '€170 Tsd. Fehlbetrag durch diese 5 Rechnungen · Zeile anklicken für Details'],
          ['>vs trend</div>', '>ggü. Trend</div>'],
          ['Top 5 risk exposures', 'Top 5 Risiken'],
          ['Total at risk: €344K · ', 'Gesamtrisiko: €344 Tsd. · '],
          [' highest</div>', ' am höchsten</div>'],
          ['>Risk score</span>', '>Risiko-Score</span>'],
          ['2 broken PTPs · sentiment declining', '2 gebrochene Zahlungszusagen · Stimmung sinkt'],
          ['DSO trend +9 days · last call 12d ago', 'DSO-Trend +9 Tage · letzter Anruf vor 12 T'],
          ['New CFO · payment behavior unclear', 'Neuer CFO · Zahlungsverhalten unklar'],
          ['Subscription dispute open', 'Abo-Streitfall offen'],
          ['POD discrepancy under review', 'POD-Abweichung in Prüfung'],
        ],
      },
      'p-04-recommend': {
        title: 'Schritt 4 · Veros Plan',
        body: 'Drei Risikosignale summieren sich. Veros Plan: <span class="grad">jetzt handeln</span>, bevor der Einbruch eintritt.',
        i18n: [
          ['Vero · Risk analysis complete', 'Vero · Risikoanalyse abgeschlossen'],
          [' · PTP due Fri 25 Apr', ' · Zahlungszusage fällig Fr 25. Apr'],
          [' 88% slip risk', ' 88 % Rutschrisiko'],
          ["Why I'm flagging this", 'Warum ich das markiere'],
          ['DSO trend:</strong> +8 days vs Q1 average', 'DSO-Trend:</strong> +8 Tage ggü. Q1-Schnitt'],
          ['>trending wrong</span>', '>falsche Richtung</span>'],
          ['2 PTPs broken</strong> in the last 60 days', '2 Zahlungszusagen gebrochen</strong> in den letzten 60 Tagen'],
          ['>€420K total</span>', '>€420 Tsd. gesamt</span>'],
          ['Sentiment declining</strong> on last 3 calls', 'Stimmung sinkt</strong> in den letzten 3 Anrufen'],
          ['positive → neutral → cautious', 'positiv, neutral, vorsichtig'],
          ["What I'd do", 'Was ich tun würde'],
          ['Place a verification call before Friday', 'Vor Freitag einen Bestätigungsanruf tätigen'],
          ['In Portuguese, light-touch · re-confirm timing without escalation', 'Auf Portugiesisch, kurz · Termin bestätigen ohne Eskalation'],
          ['Move to priority collections queue', 'In den Prioritäts-Arbeitsvorrat verschieben'],
          ['If no response by Thursday, escalate to ', 'Bei keiner Antwort bis Donnerstag eskalieren an '],
          ["'s manager</div>", 's Vorgesetzten</div>'],
          ['5 invoices</strong> rescored', '5 Rechnungen</strong> neu bewertet'],
          ['Forecast</strong> auto-updates if applied', 'Prognose</strong> aktualisiert sich automatisch'],
          ['Audit trail</strong> attached', 'Audit-Trail</strong> angehängt'],
          ['Reversible from the queue if circumstances change.', 'Aus der Liste rücknehmbar, falls sich die Lage ändert.'],
          ['Adjust plan', 'Plan anpassen'],
          ["Apply Vero's plan →", 'Veros Plan anwenden →'],
        ],
      },
      'p-05-resolved': {
        title: 'Schritt 5 · Prognose stabilisiert',
        body: 'Einbruch abgewendet. Prognose wieder im Trend. Soll Vero diese Signale <span class="grad">überwachen und darauf reagieren</span>, jeden Morgen?',
        i18n: [
          ['>Forecast restored</h3>', '>Prognose stabilisiert</h3>'],
          ['Verification call placed · ', 'Bestätigungsanruf getätigt · '],
          [' reaffirmed Fri 25 Apr · backup escalation queued', ' bestätigt erneut Fr 25. Apr · Backup-Eskalation eingereiht'],
          ['€170K dip avoided', '€170 Tsd.-Einbruch vermieden'],
          ["13-week cash forecast · after Vero's plan", '13-Wochen-Liquiditätsplanung · nach Veros Plan'],
          ['+€50K vs prior forecast at week 13', '+€50 Tsd. ggü. vorheriger Prognose in Woche 13'],
          ['>Week 6</div>', '>Woche 6</div>'],
          ['>Week 13</div>', '>Woche 13</div>'],
          ['>PTPs at risk<', '>Gefährdete Zahlungszusagen<'],
          ['>Confidence</div>', '>Sicherheit</div>'],
          ['I rescore your forecast every morning. Want me to surface and act on signals like this automatically — within your thresholds?', 'Ich bewerte Ihre Prognose jeden Morgen neu. Soll ich Signale wie dieses automatisch aufzeigen und darauf reagieren, innerhalb Ihrer Grenzen?'],
          ['Yes, monitor', 'Ja, überwachen'],
          ['Just notify me', 'Nur benachrichtigen'],
        ],
      },
    },
  },

  /* ═══════════════════════ VERO AGENT (chat v2) ═══════════════════════ */
  'vero-chat-v2': {
    tag: 'VERO AGENT · INTERAKTIVE DEMO',
    coverLabel: 'Lernen Sie Vero kennen, Ihre AR-Teamleitung',
    closing: {
      headline: 'Geprüft, freigegeben, gestartet. <span class="grad">Ein Agent</span> steuert Ihre Debitoren.',
      sub: 'So könnten Ihre Morgen aussehen.',
    },
    scenes: {
      'vb-01-recap': {
        title: 'Schritt 1 · Nachtzusammenfassung',
        body: 'Vero hat die offensichtliche Arbeit schon erledigt. Hier ist, was noch <span class="grad">auf Sie wartet</span>.',
        i18n: [
          ['● Recap ready · composed 0:00:12 ago', '● Zusammenfassung bereit · vor 0:00:12 erstellt'],
          ['>Tuesday, 08:00</span>', '>Dienstag, 08:00</span>'],
          ['>Done overnight</span>', '>Über Nacht erledigt</span>'],
          ['12 PDFs extracted', '12 PDFs extrahiert'],
          ['10 invoices matched', '10 Rechnungen zugeordnet'],
          ['8 JEs posted', '8 Buchungen gebucht'],
          ['5 deductions resolved', '5 Abzüge geklärt'],
          ['14h 28m unattended', '14 Std. 28 Min. unbeaufsichtigt'],
          ['Good morning, Sarah.</strong> ', 'Guten Morgen, Sarah.</strong> '],
          ['€847K cleared</span>', '€847 Tsd. ausgeglichen</span>'],
          [' overnight. <span class="num-amber">', ' über Nacht. <span class="num-amber">'],
          ['>3 buckets</span>', '>3 Bereiche</span>'],
          ["couldn't go autonomous without your eyes. Q2 forecast upgraded ", 'konnten nicht ohne Ihr Auge autonom laufen. Q2-Prognose angehoben '],
          ['>Cash application</div>', '>Cash Application</div>'],
          ['2 need your review', '2 zur Prüfung'],
          [' on 8 auto-posted JEs. Two edge cases drafted and waiting.', ' auf 8 automatisch gebuchten Buchungen. Zwei Grenzfälle entworfen und wartend.'],
          ['>Collections · today</div>', '>Collections · heute</div>'],
          ['3 calls to approve', '3 Anrufe freigeben'],
          ["Top 3 priorities I'd work. ", 'Top-3-Prioritäten, die ich bearbeiten würde. '],
          ['€279K recovery</span> projected.', '€279 Tsd. Rückholung</span> erwartet.'],
          ['>Deductions</div>', '>Abzüge</div>'],
          ['1 needs you', '1 braucht Sie'],
          ["<span class=\"num-green\">5 resolved</span> autonomously. One €450 portion I couldn't explain, packaged for you.", '<span class="num-green">5 geklärt</span> autonom. Einen Anteil von €450 konnte ich nicht erklären, für Sie gebündelt.'],
          ['>Q2 forecast · impact</div>', '>Q2-Prognose · Wirkung</div>'],
          ['+€1.2M WoW', '+€1,2 Mio. ggü. Vorwoche'],
          ['Upgraded to <span class="num-violet">€14.6M</span>. Driven by 8 PTP captures, lower DSO on 5 accounts.', 'Angehoben auf <span class="num-violet">€14,6 Mio.</span>. Getrieben durch 8 Zahlungszusagen, niedrigeres DSO bei 5 Konten.'],
          ['<strong>6</strong> items for you', '<strong>6</strong> Punkte für Sie'],
          ['<strong>€279K</strong> to recover', '<strong>€279 Tsd.</strong> zurückzuholen'],
          ['<strong>~2h</strong> time back', '<strong>~2 Std.</strong> Zeit zurück'],
          ['Walk me through each bucket, one approval at a time', 'Führe mich Bereich für Bereich durch, eine Freigabe nach der anderen'],
          ['2 JEs · 3 calls · 1 deduction · nothing fires until you say yes', '2 Buchungen · 3 Anrufe · 1 Abzug · nichts startet, bis Sie zustimmen'],
          ['Review &amp; approve', 'Prüfen &amp; freigeben'],
          ['Ask a follow-up...', 'Folgefrage stellen...'],
        ],
      },
      'vb-02-jes': {
        title: 'Schritt 2 · Cash App · 2 Buchungen',
        body: 'Jede Buchungszeile ist sichtbar. Keine Blackbox, <span class="grad">keine Überraschungen</span>.',
        i18n: [
          ['● Reviewing · step 1 of 3 · cash application', '● Prüfung · Schritt 1 von 3 · Cash Application'],
          ['2 of 6 items', '2 von 6 Punkten'],
          ['Two journal entries sit below my auto-post threshold. Both drafted, both balanced, full evidence attached:', 'Zwei Journalbuchungen liegen unter meiner Automatik-Schwelle. Beide entworfen, beide ausgeglichen, vollständige Nachweise angehängt:'],
          ['Cash application · 2 edge cases for your approval', 'Cash Application · 2 Grenzfälle zur Freigabe'],
          ["Already cleared overnight: 8 JEs, €847K. These 2 didn't hit auto-post.", 'Über Nacht bereits ausgeglichen: 8 Buchungen, €847 Tsd.. Diese 2 erreichten die Automatik nicht.'],
          ['>Balanced</span>', '>Ausgeglichen</span>'],
          ['Wire €530,000 · match confidence 87% · 1 line needs split between INV-0021 and INV-0023', 'Überweisung €530.000 · Treffersicherheit 87 % · 1 Zeile aufzuteilen zwischen INV-0021 und INV-0023'],
          ['87% · below threshold', '87 % · unter Schwelle'],
          ['<strong>Why you:</strong> short €230 between invoices, fits trade promo pattern, but my threshold is 95%. Your call.', '<strong>Warum Sie:</strong> €230 Differenz zwischen Rechnungen, passt zum Trade-Promo-Muster, aber meine Schwelle ist 95 %. Ihre Entscheidung.'],
          ['<th>Account</th>', '<th>Konto</th>'],
          ['<th>Description</th>', '<th>Beschreibung</th>'],
          ['>Debit</th>', '>Soll</th>'],
          ['>Credit</th>', '>Haben</th>'],
          [' · AR Acme Industries<', ' · Debitoren Acme Industries<'],
          ['>Wire receipt<', '>Überweisungseingang<'],
          ['>Clear INV-0019<', '>INV-0019 ausgleichen<'],
          ['>Clear INV-0020<', '>INV-0020 ausgleichen<'],
          ['>Clear INV-0021 plus net<', '>INV-0021 plus Netto ausgleichen<'],
          ['>Totals</span>', '>Summen</span>'],
          ['>balanced</span>', '>ausgeglichen</span>'],
          ['Wire €92,400 · match confidence 81% · FX rate EUR/USD locked at 1.084', 'Überweisung €92.400 · Treffersicherheit 81 % · FX-Kurs EUR/USD fixiert bei 1.084'],
          ['81% · below threshold', '81 % · unter Schwelle'],
          ['<strong>Why you:</strong> cross-currency conversion. Want you to confirm the rate against treasury lock before posting.', '<strong>Warum Sie:</strong> Fremdwährungsumrechnung. Bitte bestätigen Sie den Kurs gegen den Treasury-Lock vor der Buchung.'],
          ['Wire receipt $100,000 at 1.084', 'Überweisungseingang $100,000 zu 1.084'],
          ['>FX clearing<', '>FX-Verrechnung<'],
          ['>Lock variance<', '>Lock-Differenz<'],
          [' · AR Acme Pharma<', ' · Debitoren Acme Pharma<'],
          ['>Clear INV-P-0055<', '>INV-P-0055 ausgleichen<'],
          ['Post both as drafted, or edit either one first', 'Beide wie entworfen buchen oder zuerst eine bearbeiten'],
          ['Posts to SAP instantly · audit trail preserved · reversible from the journal list', 'Bucht sofort in SAP · Audit-Trail erhalten · aus der Journalliste rücknehmbar'],
          [' Approve both JEs', ' Beide Buchungen freigeben'],
          ['Or ask me to edit either one...', 'Oder bitten Sie mich, eine zu bearbeiten...'],
        ],
      },
      'vb-03-calls': {
        title: 'Schritt 3 · Collections · 3 Anrufe',
        body: 'Skript, Sprache und Zeit je Kunde. Vero wartet auf Ihr <span class="grad">Startsignal</span>.',
        i18n: [
          ['● Reviewing · step 2 of 3 · collections', '● Prüfung · Schritt 2 von 3 · Collections'],
          ['3 of 6 items', '3 von 6 Punkten'],
          ['Three priority collections today. Projected recovery ', 'Drei Prioritäts-Collections heute. Erwartete Rückholung '],
          ["€279K</span>. Each one has the customer, language, script I'd use, and timing. Approve any or all.", '€279 Tsd.</span>. Jeder enthält Kunde, Sprache, mein Skript und Zeitpunkt. Geben Sie einzelne oder alle frei.'],
          ['Collections queue · 3 calls ready', 'Collections-Liste · 3 Anrufe bereit'],
          ['Light-touch, per your playbook, fallback to email on voicemail', 'Kurzkontakt, nach Ihrem Playbook, Rückfall auf E-Mail bei Mailbox'],
          ['€279K projected', '€279 Tsd. erwartet'],
          ['>Why</span>', '>Warum</span>'],
          ['Verify Friday PTP. Has broken 2 PTPs in 60d, sentiment declined last 3 calls.', 'Freitags-Zahlungszusage bestätigen. Hat 2 Zahlungszusagen in 60 T gebrochen, Stimmung in letzten 3 Anrufen gesunken.'],
          ['>Portuguese</span>', '>Portugiesisch</span>'],
          ['>Light-touch</span>', '>Kurzkontakt</span>'],
          ['DSO drift, 9 days over Q1 average, no response to last email 12 days ago.', 'DSO-Drift, 9 Tage über Q1-Schnitt, keine Antwort auf letzte E-Mail vor 12 Tagen.'],
          ['>German</span>', '>Deutsch</span>'],
          ['>Check-in</span>', '>Nachfassen</span>'],
          ['New CFO joined 30d ago. No payment history yet, intro call to set cadence.', 'Neuer CFO seit 30 T. Noch keine Zahlungshistorie, Vorstellungsanruf zur Rhythmus-Abstimmung.'],
          ['>English</span>', '>Englisch</span>'],
          ['>Intro</span>', '>Vorstellung</span>'],
          ['Historical hit-rate on calls like these: <strong>72%</strong>. Projected cash unlocked this week <strong>€201K</strong> (weighted).', 'Historische Erfolgsquote bei solchen Anrufen: <strong>72 %</strong>. Erwartete freigesetzte Liquidität diese Woche <strong>€201 Tsd.</strong> (gewichtet).'],
          ["Schedule all three, or decline any I've misjudged", 'Alle drei planen oder einzelne ablehnen, die ich falsch eingeschätzt habe'],
          ['SIP trunk · transcript + sentiment captured per call · written summary in your inbox after', 'SIP-Trunk · Transkript und Stimmung je Anruf erfasst · schriftliche Zusammenfassung danach in Ihrem Posteingang'],
          [' Approve 3 calls', ' 3 Anrufe freigeben'],
          ['Or say &lsquo;skip the Motors call&rsquo;...', 'Oder sagen Sie „Motors-Anruf überspringen"...'],
        ],
      },
      'vb-04-flag': {
        title: 'Schritt 4 · Abzüge · 1 Markierung',
        body: 'Vero hat 5 selbst geklärt. Dieser stieß an die <span class="grad">Leitplanke</span>, für Sie gebündelt.',
        i18n: [
          ['● Reviewing · step 3 of 3 · deductions', '● Prüfung · Schritt 3 von 3 · Abzüge'],
          ['6 of 6 items', '6 von 6 Punkten'],
          ["I cleared <span class=\"num-green\">5 short-pays</span> overnight. One €450 portion I couldn't explain against your rules, so I stopped and packaged it:", 'Ich habe <span class="num-green">5 Kürzungen</span> über Nacht geklärt. Einen Anteil von €450 konnte ich anhand Ihrer Regeln nicht erklären, also habe ich gestoppt und ihn gebündelt:'],
          ['Deductions · 1 case needs your call', 'Abzüge · 1 Fall braucht Ihre Entscheidung'],
          ['5 others auto-settled to trade promo reserve, no action needed', '5 weitere automatisch auf Trade-Promo-Rückstellung gebucht, keine Aktion nötig'],
          ['€450 unexplained', '€450 unerklärt'],
          [' · short-pay investigation', ' · Kürzungsuntersuchung'],
          ['INV-3482 · expected €92,000 · received €87,770 · short €4,230', 'INV-3482 · erwartet €92.000 · erhalten €87.770 · Kürzung €4.230'],
          ['€450 flagged', '€450 markiert'],
          ['I already resolved', 'Bereits erledigt'],
          ['€3,780 matched to trade promo TP-041 (89%)', '€3.780 dem Trade-Promo TP-041 zugeordnet (89 %)'],
          ['Evidence pack assembled · 5 docs linked', 'Nachweispaket erstellt · 5 Belege verknüpft'],
          ['GL entry drafted · ready on approval', 'Buchung entworfen · bereit bei Freigabe'],
          ['Why I stopped · €450', 'Warum ich gestoppt habe · €450'],
          ['<strong>No promo, PO line, or POD note</strong> I could match to this €450 portion. Could be a one-off discount agreed off-system, a missed trade allowance, or a short-pay error.', '<strong>Kein Promo, keine Bestellzeile, kein POD-Vermerk</strong>, den ich diesem €450-Anteil zuordnen konnte. Könnte ein einmaliger, außerhalb des Systems vereinbarter Rabatt sein, eine übersehene Handelsvergütung oder ein Kürzungsfehler.'],
          ['Cross-referenced: 1,247 historical cases · TP-041 rate card · ', 'Abgeglichen: 1,247 historische Fälle · TP-041-Konditionen · '],
          ["'s last 3 emails. No matches above 62%.", 's letzte 3 E-Mails. Keine Treffer über 62 %.'],
          ['Send to your dispute queue with evidence pack attached', 'Mit Nachweispaket in Ihre Streitfall-Liste senden'],
          ['€3,780 auto-settlement waits for your approval in the Deductions module', '€3.780 Auto-Ausgleich wartet auf Ihre Freigabe im Deductions-Modul'],
          [' Send to my queue', ' In meine Liste senden'],
          ['Or tell me how to resolve it...', 'Oder sagen Sie mir, wie ich es klären soll...'],
        ],
      },
      'vb-05-schedule': {
        title: 'Schritt 5 · Als Task planen',
        body: 'Sechs Punkte in drei Klicks. Lassen Sie Vero diesen Morgen <span class="grad">jeden Morgen</span> ausführen.',
        i18n: [
          ['● Queue approved · all actions fired · 0:00:08', '● Arbeitsvorrat freigegeben · alle Aktionen gestartet · 0:00:08'],
          ['6 of 6 done', '6 von 6 erledigt'],
          ['All six items fired. ', 'Alle sechs Punkte gestartet. '],
          ["Here's the scorecard:", 'Hier ist die Auswertung:'],
          ['This morning · executed', 'Heute Morgen · ausgeführt'],
          ['>JEs posted<', '>Buchungen gebucht<'],
          ['€622K cleared', '€622 Tsd. ausgeglichen'],
          ['>Calls firing<', '>Anrufe starten<'],
          ['€279K projected', '€279 Tsd. erwartet'],
          ['>Deduction flagged<', '>Abzug markiert<'],
          ['>in your queue<', '>in Ihrer Liste<'],
          ['>Time back<', '>Zeit zurück<'],
          ['vs prior morning', 'ggü. vorherigem Morgen'],
          ['>Schedule this</span>', '>Das planen</span>'],
          ['You approved every item this morning. That pattern has held <strong>6 mornings in a row</strong>. Promote this to a daily task and Vero will run it unprompted, surfacing only exceptions. <strong>~12 hours a month back.</strong>', 'Sie haben heute jeden Punkt freigegeben. Dieses Muster hält seit <strong>6 Morgen in Folge</strong>. Machen Sie daraus einen täglichen Task, und Vero führt ihn unaufgefordert aus und zeigt nur Ausnahmen. <strong>~12 Stunden im Monat zurück.</strong>'],
          ['>When</span>', '>Wann</span>'],
          ['Daily, 08:00 local', 'Täglich, 08:00 Ortszeit'],
          ['>Auto-fire at</span>', '>Auto-Start bei</span>'],
          ['≥ 95% confidence per item', '≥ 95 % Sicherheit je Punkt'],
          ['>Escalate</span>', '>Eskalieren</span>'],
          ['exceptions and flags to you', 'Ausnahmen und Markierungen an Sie'],
          [' Schedule as daily task', ' Als täglichen Task planen'],
          ['Keep approving manually', 'Weiter manuell freigeben'],
          ['Ask a follow-up...', 'Folgefrage stellen...'],
        ],
      },
    },
  },
};
